name: Security Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  trivy-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master

        with:
          scan-type: fs
          scan-ref: .
          format: table
          output: trivy-report.txt
          exit-code: "0"

      - name: Verify Report

        run: |
          ls -la
          cat trivy-report.txt

      - name: Upload Trivy Report

        uses: actions/upload-artifact@v4

        with:
          name: trivy-report
          path: trivy-report.txt
          retention-days: 30
